"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { Archive, Cpu, Database, Download, FileJson, Plus, RotateCcw, Save, Settings2, SlidersHorizontal, Upload } from "lucide-react";
import { readConfig, useConfig } from "@/hooks/use-config";
import { AppConfig, Capability, GpuConfig, ModelConfig, TaskRule, cloneDefaultConfig, validateConfig } from "@/lib/config";

type Section = "models"|"gpus"|"assumptions"|"tasks"|"exchange";
const CAPABILITIES: Capability[]=["текст","код","изображения","инструменты","длинный контекст","агенты"];
const sectionMeta:Record<Section,{title:string;desc:string}>={
  models:{title:"Каталог моделей",desc:"Характеристики, возможности и минимальные конфигурации запуска"},
  gpus:{title:"Каталог GPU и цены",desc:"Память, узлы, энергопотребление, покупка и аренда"},
  assumptions:{title:"Допущения TCO",desc:"Глобальные финансовые и инфраструктурные коэффициенты"},
  tasks:{title:"Правила задач",desc:"Требования, на основании которых калькулятор допускает модели"},
  exchange:{title:"Импорт, экспорт и восстановление",desc:"Перенос согласованных параметров и возврат к исходным значениям"}
};
const num=(value:string)=>Number.isFinite(+value)?+value:0;

export default function SettingsPage(){
  const {config:live,save,reset,loaded}=useConfig();
  const [draft,setDraft]=useState<AppConfig>(cloneDefaultConfig);
  const [section,setSection]=useState<Section>("models");
  const [errors,setErrors]=useState<string[]>([]);
  const [message,setMessage]=useState("");
  const fileRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(loaded)setDraft(live)},[loaded,live]);
  const dirty=useMemo(()=>JSON.stringify(draft)!==JSON.stringify(live),[draft,live]);
  useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard)},[dirty]);

  const updateModel=(id:string,patch:Partial<ModelConfig>)=>setDraft(c=>({...c,models:c.models.map(x=>x.id===id?{...x,...patch}:x)}));
  const updateGpu=(id:string,patch:Partial<GpuConfig>)=>setDraft(c=>({...c,gpus:c.gpus.map(x=>x.id===id?{...x,...patch}:x)}));
  const updateTask=(id:string,patch:Partial<TaskRule>)=>setDraft(c=>({...c,tasks:c.tasks.map(x=>x.id===id?{...x,...patch}:x)}));
  const addModel=()=>{const n=Date.now();setDraft(c=>({...c,models:[...c.models,{id:`model-${n}`,enabled:true,name:"Новая модель",developer:"",architecture:"MoE",totalParamsB:100,activeParamsB:20,contextK:128,bitsPerWeight:4,level:2,capabilities:["текст"],recommendedGpuId:c.gpus[0]?.id??"",minGpuCount:1,sessionsPerReplica:4,precision:"INT4",license:"Требует проверки",note:"",sourceUrl:"",sourceDate:new Date().toISOString().slice(0,10),evidence:"Инженерная оценка"}]}))};
  const duplicateModel=(source:ModelConfig)=>{const n=Date.now();setDraft(c=>({...c,models:[...c.models,{...source,id:`${source.id}-copy-${n}`,name:`${source.name} — копия`,evidence:"Инженерная оценка"}]}))};
  const addGpu=()=>{const n=Date.now();setDraft(c=>({...c,gpus:[...c.gpus,{id:`gpu-${n}`,enabled:true,name:"Новый GPU",vendor:"",memoryGb:80,nodeGpuCount:8,nodePriceRub:0,rentPerGpuHourRub:0,nodePowerKw:8,memoryBandwidthTb:0,interconnect:"",priceKind:"Инженерная оценка",sourceLabel:"",sourceUrl:"",sourceDate:new Date().toISOString().slice(0,10)}]}))};
  const addTask=()=>{const n=Date.now();setDraft(c=>({...c,tasks:[...c.tasks,{id:`task-${n}`,enabled:true,title:"Новая задача",description:"",category:"",minLevel:2,minContextK:128,requiredCapabilities:["текст"]}]}))};
  const handleSave=()=>{const found=validateConfig(draft);if(found.length){setErrors(found);setMessage("");return}const result=save(draft);if(result.length){setErrors(result);return}setDraft(readConfig());setErrors([]);setMessage("Настройки сохранены. Калькулятор уже использует новую ревизию.")};
  const discard=()=>{setDraft(live);setErrors([]);setMessage("Изменения отменены.")};
  const exportConfig=()=>{const blob=new Blob([JSON.stringify(draft,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`gpu-calculator-settings-r${draft.revision}.json`;a.click();URL.revokeObjectURL(url);setMessage("Файл параметров экспортирован.")};
  const importConfig=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setErrors(["Файл превышает допустимый размер 2 МБ."]);return}try{const parsed=JSON.parse(await file.text()) as AppConfig;const found=validateConfig(parsed);if(found.length){setErrors(found);return}setDraft(parsed);setErrors([]);setMessage("Файл проверен и загружен в черновик. Нажмите «Сохранить изменения».")}catch{setErrors(["Не удалось прочитать JSON-файл."])}finally{e.target.value=""}};
  const resetAll=()=>{if(!window.confirm("Вернуть все модели, GPU, цены и коэффициенты к исходным значениям?"))return;reset();const fresh=cloneDefaultConfig();setDraft(fresh);setErrors([]);setMessage("Исходные параметры восстановлены.")};

  return <main className="page-shell">
    <div className="page-heading"><div><div className="eyebrow"><Settings2 size={15}/>Управление расчётной моделью</div><h1>Параметры калькулятора</h1></div><p>Изменяйте каталоги моделей и оборудования, цены, правила подбора и все составляющие совокупной стоимости владения.</p></div>
    <div className="settings-layout">
      <aside className="panel settings-nav">
        <button className={section==="models"?"active":""} onClick={()=>setSection("models")}><Database size={16}/>Модели <span>({draft.models.length})</span></button>
        <button className={section==="gpus"?"active":""} onClick={()=>setSection("gpus")}><Cpu size={16}/>GPU и цены <span>({draft.gpus.length})</span></button>
        <button className={section==="assumptions"?"active":""} onClick={()=>setSection("assumptions")}><SlidersHorizontal size={16}/>Допущения TCO</button>
        <button className={section==="tasks"?"active":""} onClick={()=>setSection("tasks")}><Settings2 size={16}/>Правила задач <span>({draft.tasks.length})</span></button>
        <button className={section==="exchange"?"active":""} onClick={()=>setSection("exchange")}><FileJson size={16}/>Импорт и экспорт</button>
        <div className="local-warning">Изменения сохраняются локально в этом браузере и не меняют параметры у других пользователей.</div>
      </aside>
      <section className="settings-main">
        <div className="settings-toolbar"><div><h2>{sectionMeta[section].title}</h2><p>{sectionMeta[section].desc}</p></div><div className="action-row"><button className="button" disabled={!dirty} onClick={discard}>Отменить</button><button className="button primary" disabled={!dirty} onClick={handleSave}><Save size={14}/>Сохранить изменения</button></div></div>
        {errors.length>0&&<div className="error-box"><b>Сохранение невозможно:</b><ul>{errors.map(x=><li key={x}>{x}</li>)}</ul></div>}
        {message&&<div className="success-box">{message}</div>}

        {section==="models"&&<div className="panel"><div className="panel-body" style={{paddingBottom:8}}><div className="card-title-row"><div><b>{draft.models.filter(x=>x.enabled).length} активных моделей</b><div className="task-desc">Диапазон от компактных моделей до 2,8 трлн параметров</div></div><button className="button" onClick={addModel}><Plus size={14}/>Добавить модель</button></div></div><div className="config-table-wrap"><table className="config-table"><thead><tr><th>Активна</th><th>Модель и разработчик</th><th>Архитектура</th><th>Параметры, млрд</th><th>Контекст, тыс.</th><th>Уровень</th><th>Возможности</th><th>GPU / количество</th><th>Точность</th><th>Источник и статус</th><th/></tr></thead><tbody>{draft.models.map(model=><tr key={model.id}>
          <td><button className={`toggle ${model.enabled?"on":""}`} onClick={()=>updateModel(model.id,{enabled:!model.enabled})}><i/></button></td>
          <td><input className="table-input wide" value={model.name} onChange={e=>updateModel(model.id,{name:e.target.value})}/><input className="table-input" style={{marginTop:5}} value={model.developer} placeholder="Разработчик" onChange={e=>updateModel(model.id,{developer:e.target.value})}/><div className="task-desc">ID: {model.id}</div></td>
          <td><select className="table-input" value={model.architecture} onChange={e=>updateModel(model.id,{architecture:e.target.value as "Dense"|"MoE"})}><option>Dense</option><option>MoE</option></select></td>
          <td><input className="table-input" type="number" value={model.totalParamsB} onChange={e=>updateModel(model.id,{totalParamsB:num(e.target.value)})}/><input className="table-input" style={{marginTop:5}} type="number" title="Активные параметры" value={model.activeParamsB} onChange={e=>updateModel(model.id,{activeParamsB:num(e.target.value)})}/></td>
          <td><input className="table-input" type="number" value={model.contextK} onChange={e=>updateModel(model.id,{contextK:num(e.target.value)})}/></td>
          <td><input className="table-input" type="number" min="1" max="5" value={model.level} onChange={e=>updateModel(model.id,{level:num(e.target.value)})}/></td>
          <td><input className="table-input wide" value={model.capabilities.join(", ")} onChange={e=>updateModel(model.id,{capabilities:e.target.value.split(",").map(x=>x.trim()).filter(x=>CAPABILITIES.includes(x as Capability)) as Capability[]})}/></td>
          <td><select className="table-input" value={model.recommendedGpuId} onChange={e=>updateModel(model.id,{recommendedGpuId:e.target.value})}>{draft.gpus.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><input className="table-input" style={{marginTop:5}} type="number" value={model.minGpuCount} onChange={e=>updateModel(model.id,{minGpuCount:num(e.target.value)})}/></td>
          <td><input className="table-input" value={model.precision} onChange={e=>updateModel(model.id,{precision:e.target.value})}/><input className="table-input" style={{marginTop:5}} type="number" title="Бит на вес" value={model.bitsPerWeight} onChange={e=>updateModel(model.id,{bitsPerWeight:num(e.target.value)})}/></td>
          <td><select className="table-input wide" value={model.evidence} onChange={e=>updateModel(model.id,{evidence:e.target.value as ModelConfig["evidence"]})}><option>Публичная рекомендация</option><option>Проверено поставщиком</option><option>Инженерная оценка</option></select><input className="table-input wide" style={{marginTop:5}} value={model.sourceUrl} placeholder="URL источника" onChange={e=>updateModel(model.id,{sourceUrl:e.target.value})}/></td>
          <td><div className="table-actions"><button className="icon-button" title="Дублировать" onClick={()=>duplicateModel(model)}><Plus size={14}/></button><button className="icon-button" title="Архивировать" onClick={()=>updateModel(model.id,{enabled:false})}><Archive size={14}/></button></div></td>
        </tr>)}</tbody></table></div></div>}

        {section==="gpus"&&<div className="panel"><div className="panel-body" style={{paddingBottom:8}}><div className="card-title-row"><div><b>{draft.gpus.filter(x=>x.enabled).length} активных ускорителей</b><div className="task-desc">Публичные значения и оценки явно разделены</div></div><button className="button" onClick={addGpu}><Plus size={14}/>Добавить GPU</button></div></div><div className="config-table-wrap"><table className="config-table"><thead><tr><th>Активен</th><th>GPU</th><th>Память, ГБ</th><th>GPU в узле</th><th>Покупка узла, ₽</th><th>Аренда GPU-час, ₽</th><th>Мощность узла, кВт</th><th>Межсоединение</th><th>Статус цены</th><th>Источник</th><th/></tr></thead><tbody>{draft.gpus.map(gpu=><tr key={gpu.id}>
          <td><button className={`toggle ${gpu.enabled?"on":""}`} onClick={()=>updateGpu(gpu.id,{enabled:!gpu.enabled})}><i/></button></td><td><input className="table-input wide" value={gpu.name} onChange={e=>updateGpu(gpu.id,{name:e.target.value})}/><input className="table-input" style={{marginTop:5}} value={gpu.vendor} onChange={e=>updateGpu(gpu.id,{vendor:e.target.value})}/><div className="task-desc">ID: {gpu.id}</div></td>
          <td><input className="table-input" type="number" value={gpu.memoryGb} onChange={e=>updateGpu(gpu.id,{memoryGb:num(e.target.value)})}/></td><td><input className="table-input" type="number" value={gpu.nodeGpuCount} onChange={e=>updateGpu(gpu.id,{nodeGpuCount:num(e.target.value)})}/></td><td><input className="table-input" type="number" value={gpu.nodePriceRub} onChange={e=>updateGpu(gpu.id,{nodePriceRub:num(e.target.value)})}/></td><td><input className="table-input" type="number" step="0.01" value={gpu.rentPerGpuHourRub} onChange={e=>updateGpu(gpu.id,{rentPerGpuHourRub:num(e.target.value)})}/></td><td><input className="table-input" type="number" step="0.1" value={gpu.nodePowerKw} onChange={e=>updateGpu(gpu.id,{nodePowerKw:num(e.target.value)})}/></td><td><input className="table-input wide" value={gpu.interconnect} onChange={e=>updateGpu(gpu.id,{interconnect:e.target.value})}/></td>
          <td><select className="table-input wide" value={gpu.priceKind} onChange={e=>updateGpu(gpu.id,{priceKind:e.target.value as GpuConfig["priceKind"]})}><option>Публичная цена</option><option>Коммерческая оценка</option><option>Инженерная оценка</option></select></td><td><input className="table-input wide" value={gpu.sourceLabel} placeholder="Источник" onChange={e=>updateGpu(gpu.id,{sourceLabel:e.target.value})}/><input className="table-input wide" style={{marginTop:5}} value={gpu.sourceUrl} placeholder="URL" onChange={e=>updateGpu(gpu.id,{sourceUrl:e.target.value})}/></td><td><button className="icon-button" title="Архивировать" onClick={()=>updateGpu(gpu.id,{enabled:false})}><Archive size={14}/></button></td>
        </tr>)}</tbody></table></div></div>}

        {section==="assumptions"&&<div className="panel settings-card"><h3>Финансовые и эксплуатационные параметры</h3><div className="settings-form-grid">{([
          ["defaultHoursMonth","Использование по умолчанию, ч/мес."],["defaultYears","Горизонт по умолчанию, лет"],["defaultConcurrency","Параллельность по умолчанию"],["electricityRubKwh","Электроэнергия, ₽/кВт·ч"],["pue","PUE центра обработки данных"],["supportPctCapexYear","Поддержка, % CAPEX/год"],["fitoutPctCapex","Ввод в эксплуатацию, % CAPEX"],["idlePowerPct","Мощность в ожидании, %"],["memoryOverheadPct","Запас памяти, %"],["usableMemoryPct","Используемая память GPU, %"],["rackMonthPerNodeRub","Размещение узла, ₽/мес."],["networkStorageMonthRub","Сеть и хранилище, ₽/мес."],["operationsMonthRub","Команда эксплуатации, ₽/мес."],["rentalServicePct","Надбавка к аренде, %"],["contingencyPct","Непредвиденные затраты, %"],["residualValuePct","Остаточная стоимость, %"],["stalePriceDays","Срок актуальности цены, дней"]
        ] as Array<[keyof AppConfig["assumptions"],string]>).map(([key,label])=><label className="field" key={key}><span>{label}</span><input className="control" type="number" step="0.1" value={draft.assumptions[key]} onChange={e=>setDraft(c=>({...c,assumptions:{...c.assumptions,[key]:num(e.target.value)}}))}/></label>)}</div></div>}

        {section==="tasks"&&<div className="panel"><div className="panel-body" style={{paddingBottom:8}}><div className="card-title-row"><div><b>Правила «задача → модель»</b><div className="task-desc">Новая бизнес-задача добавляется без изменения программного кода</div></div><button className="button" onClick={addTask}><Plus size={14}/>Добавить задачу</button></div></div><div className="config-table-wrap"><table className="config-table"><thead><tr><th>Активна</th><th>Название</th><th>Описание</th><th>Категория</th><th>Уровень</th><th>Контекст, тыс.</th><th>Обязательные возможности</th><th/></tr></thead><tbody>{draft.tasks.map(task=><tr key={task.id}><td><button className={`toggle ${task.enabled?"on":""}`} onClick={()=>updateTask(task.id,{enabled:!task.enabled})}><i/></button></td><td><input className="table-input wide" value={task.title} onChange={e=>updateTask(task.id,{title:e.target.value})}/><div className="task-desc">ID: {task.id}</div></td><td><input className="table-input wide" value={task.description} onChange={e=>updateTask(task.id,{description:e.target.value})}/></td><td><input className="table-input" value={task.category} onChange={e=>updateTask(task.id,{category:e.target.value})}/></td><td><input className="table-input" type="number" min="1" max="5" value={task.minLevel} onChange={e=>updateTask(task.id,{minLevel:num(e.target.value)})}/></td><td><input className="table-input" type="number" value={task.minContextK} onChange={e=>updateTask(task.id,{minContextK:num(e.target.value)})}/></td><td><input className="table-input wide" value={task.requiredCapabilities.join(", ")} onChange={e=>updateTask(task.id,{requiredCapabilities:e.target.value.split(",").map(x=>x.trim()).filter(x=>CAPABILITIES.includes(x as Capability)) as Capability[]})}/></td><td><button className="icon-button" title="Архивировать" onClick={()=>updateTask(task.id,{enabled:false})}><Archive size={14}/></button></td></tr>)}</tbody></table></div></div>}

        {section==="exchange"&&<div className="stack"><div className="panel settings-card"><h3>Перенос параметров</h3><div className="import-zone"><FileJson size={34} color="#0d6f9c"/><b>Один JSON-файл содержит всю расчётную модель</b><p>Экспортируйте согласованную конфигурацию или загрузите файл. Импорт сначала проходит проверку и попадает в черновик.</p><div className="action-row"><button className="button" onClick={exportConfig}><Download size={14}/>Экспортировать JSON</button><button className="button" onClick={()=>fileRef.current?.click()}><Upload size={14}/>Импортировать JSON</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={importConfig}/></div></div></div><div className="panel settings-card"><div className="card-title-row"><div><h3 style={{marginBottom:4}}>Восстановление исходных значений</h3><div className="task-desc">Сброс удалит локальные изменения каталога и цен в этом браузере.</div></div><button className="button danger" onClick={resetAll}><RotateCcw size={14}/>Полный сброс</button></div></div><div className="panel settings-card"><h3>Состояние конфигурации</h3><div className="metric-grid"><div className="metric"><span>Версия схемы</span><b>{draft.schemaVersion}</b><small>совместимая</small></div><div className="metric"><span>Ревизия</span><b>{draft.revision}</b><small>{dirty?"есть несохранённые изменения":"сохранено"}</small></div><div className="metric"><span>Моделей</span><b>{draft.models.length}</b><small>{draft.models.filter(x=>x.enabled).length} активных</small></div><div className="metric"><span>GPU</span><b>{draft.gpus.length}</b><small>{draft.gpus.filter(x=>x.enabled).length} активных</small></div></div></div></div>}
      </section>
    </div>
    <footer className="footer-note"><span>Настройки первой версии хранятся в localStorage. Для общей корпоративной конфигурации потребуется серверное хранилище и управление ролями.</span><span>Ревизия {live.revision}</span></footer>
  </main>;
}
